name = "glide-site"
compatibility_date = "2026-09-26"
workers_dev = true

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true
