import { navigate } from './navigate.mjs';

/** Ploeg feeds: Insights tiles, tables and phone cards, activity days, paging and kinds, Runs filters with the table and phone cards, and proposed-work approval and rejection, at desktop and phone widths. */
export async function run({ page, assert, screenshot }) {
  const noOverflow = async label => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${label} overflows horizontally`);
  const visible = selector => page.evaluate(css => [...document.querySelectorAll(css)].filter(element => element.getClientRects().length).length, selector);
  await navigate(page, 'Insights');
  await page.getByRole('heading', { name: 'Runs and spend', exact: true }).waitFor();
  for (const viewport of [{ width: 1440, height: 1040 }, { width: 390, height: 844 }]) {
    const phone = viewport.width < 600;
    await page.setViewportSize(viewport);
    await navigate(page, 'Insights');
    await page.getByRole('heading', { name: 'Runs and spend', exact: true }).waitFor();
    await page.getByRole('button', { name: '7 days', exact: true }).click();
    await page.getByText(/^The last 7 days, across the 2 Teams your account can see\./).waitFor();
    await page.getByRole('button', { name: 'Refresh', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '7 days', exact: true }).getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('.insights .stat').count(), 9);
    assert.equal(await page.locator('.insights a.stat[href="#work?lane=needs_human"]').count(), 1, 'The Needs you tile links to its lane');
    await page.getByText('Illustrative Ploeg records. No Run executed, no model was called and spend is US$ 0,00.', { exact: true }).waitFor();
    assert.equal(await page.locator('.insights-table').first().locator('tbody tr').count(), 2);
    assert.equal(await visible('.insights-team'), phone ? 2 : 0, 'Per-Team cards replace the tables on phones');
    assert.equal(await visible('.insights-table'), phone ? 0 : 2);
    assert.equal(await page.locator('main svg polyline, main canvas').count(), 0, 'Insights must not draw a line chart');
    await noOverflow(`Insights at ${viewport.width}px`);
    await screenshot(`ploeg-overview-${viewport.width}`);
    await navigate(page, 'Activity');
    await page.locator('.activity-event').first().waitFor();
    assert.equal(await page.locator('.activity-event').count(), 10);
    await page.getByRole('heading', { name: 'Today', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Load older', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.activity-event').length === 20);
    assert.equal(new Set(await page.locator('.activity-event').evaluateAll(rows => rows.map(row => row.dataset.eventId))).size, 20, 'The activity feed repeated an event');
    assert.equal(await page.locator('.activity-event .timeline-title').evaluateAll(titles => titles.filter(title => /_|\w\.\w/.test(title.textContent)).length), 0, 'An audit action is shown by its code instead of a label');
    await page.getByLabel('Kind', { exact: true }).selectOption('work');
    assert(await page.locator('.activity-event').count() < 20);
    assert.match(page.url(), /#activity\?kind=work$/);
    await page.getByLabel('Kind', { exact: true }).selectOption('');
    await noOverflow(`Activity at ${viewport.width}px`);
    await screenshot(`ploeg-activity-${viewport.width}`);
    await navigate(page, 'Runs');
    await page.locator('.runs-table tbody tr[data-run-id]').first().waitFor({ state: 'attached' });
    assert.equal(await page.locator('.runs-table tbody tr[data-run-id]').count(), 10);
    assert.equal(await visible('.runs-card'), phone ? 10 : 0, 'Runs become cards on phones');
    assert.equal(await visible('.runs-table tbody tr[data-run-id]'), phone ? 0 : 10);
    assert.equal(await page.locator('.runs-table tbody tr[data-run-id]').first().getAttribute('data-state'), 'running', 'Running work comes first');
    await page.getByLabel('State', { exact: true }).selectOption('running');
    await page.waitForFunction(() => document.querySelectorAll('.runs-table tbody tr[data-run-id]').length === 1);
    assert.equal(await page.getByLabel('Outcome', { exact: true }).isDisabled(), true, 'Only finished Runs have an outcome');
    assert.match(page.url(), /#runs\?state=running$/);
    await page.getByLabel('State', { exact: true }).selectOption('');
    await page.waitForFunction(() => document.querySelectorAll('.runs-table tbody tr[data-run-id]').length === 10);
    await noOverflow(`Runs at ${viewport.width}px`);
    await screenshot(`ploeg-runs-${viewport.width}`);
    await navigate(page, 'Proposed');
    await page.getByRole('heading', { name: 'Add a regression test for negative half-cent totals', exact: true }).waitFor();
    await page.getByText('Ploeg does not report that budget to Vloer yet, so no amount is shown.', { exact: true }).first().waitFor();
    await noOverflow(`Proposed at ${viewport.width}px`);
    await screenshot(`ploeg-proposed-${viewport.width}`);
  }
  await page.setViewportSize({ width: 1440, height: 1040 });
  const research = page.getByRole('article', { name: 'Clarify which markets the research brief covers' });
  await research.getByRole('button', { name: 'Approve', exact: true }).click();
  const approval = page.getByRole('dialog', { name: 'Approve this proposal?' });
  await approval.getByText(/^Its Runs spend from the research Team’s budget\./).waitFor();
  await approval.getByText('Demo: approving changes only this demo’s sample data. Nothing is dispatched and nothing is spent.', { exact: true }).waitFor();
  await approval.getByRole('button', { name: 'Keep it proposed', exact: true }).click();
  await approval.waitFor({ state: 'hidden' });
  assert.equal(await page.getByRole('button', { name: 'Approve', exact: true }).count(), 2, 'Keeping it proposed changed nothing');
  await research.getByRole('button', { name: 'Reject', exact: true }).click();
  const rejection = page.getByRole('dialog', { name: 'Reject this proposal?' });
  await rejection.getByText('In this demo the proposal is withdrawn from the sample data. Nothing is dispatched.', { exact: true }).waitFor();
  await rejection.getByRole('button', { name: 'Reject', exact: true }).click();
  assert.equal(await rejection.isVisible(), true, 'A rejection without a reason was submitted');
  await rejection.getByText('Write a reason before you reject it.', { exact: true }).waitFor();
  assert.equal(await rejection.getByLabel('Reason', { exact: true }).getAttribute('aria-invalid'), 'true');
  await rejection.getByLabel('Reason', { exact: true }).fill('   ');
  await rejection.getByRole('button', { name: 'Reject', exact: true }).click();
  assert.equal(await rejection.isVisible(), true, 'A blank reason was submitted');
  await rejection.getByLabel('Reason', { exact: true }).fill('The brief already names its markets.');
  await rejection.getByRole('button', { name: 'Reject', exact: true }).click();
  await page.getByText('Recorded in this demo only. Nothing was dispatched.', { exact: true }).waitFor();
  await research.waitFor({ state: 'detached' });
  assert.equal(await page.getByRole('button', { name: 'Approve', exact: true }).count(), 1);
}
