/** The command palette: opening from the search button, `/` and Ctrl K, the combobox and listbox contract, fuzzy search with highlighted matches, arrow keys from any focus in the dialog, number jumps, recent Work Items kept per user, commands (theme, live updates, shortcuts, desktop notifications) that keep Preferences in sync, the Work Item failure notice that clears once Now loads, the no-match next step, Escape restoring focus, the phone sheet, and the favicon dot that follows what waits on you. */
export async function run({ page, app, live, password, assert, screenshot }) {
  const base = `http://127.0.0.1:${app.server.address().port}`;
  const palette = page.getByRole('dialog', { name: 'Search and commands' });
  const input = palette.getByRole('combobox', { name: 'Search pages, commands and Work Items' });
  const results = palette.getByRole('listbox', { name: 'Results' });
  const notice = palette.locator('#palette-notice');
  const hash = () => page.evaluate(() => location.hash);
  const route = async target => { await page.evaluate(next => { location.hash = next; }, target); await page.waitForFunction(next => location.hash === `#${next}` && document.getElementById('page-title'), target); };
  const active = () => page.evaluate(() => { const id = document.getElementById('palette-input')?.getAttribute('aria-activedescendant'); const option = id && document.getElementById(id); return option ? { id, selected: option.getAttribute('aria-selected'), role: option.getAttribute('role'), text: option.querySelector('.palette-option-label')?.textContent } : null; });
  const favicon = () => page.evaluate(() => document.querySelector('link[rel~="icon"]')?.getAttribute('href'));
  const first = label => page.waitForFunction(text => document.querySelector('#palette-option-0 .palette-option-label')?.textContent === text, label);
  const search = async (text, label) => {
    await page.keyboard.press('Control+k');
    await input.waitFor();
    await input.fill(text);
    if (label) await first(label);
  };
  const close = async () => { await page.keyboard.press('Escape'); await palette.waitFor({ state: 'hidden' }); };

  await page.setViewportSize({ width: 1440, height: 1040 });
  await page.goto(`${base}/#work/105`);
  await page.locator('#page-title').waitFor();
  await page.waitForFunction(() => document.querySelector('link[rel~="icon"]')?.getAttribute('href')?.startsWith('data:image/png;base64,'));
  assert.equal(await page.evaluate(() => document.querySelector('link[rel~="icon"]').getAttribute('type')), 'image/png', 'the favicon shows the dot while something waits on you');
  await route('now');
  await page.locator('.app-topbar').getByRole('button', { name: 'Search and commands' }).click();
  await input.waitFor();
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'palette-input', 'the search field takes focus');
  assert.equal(await input.getAttribute('aria-expanded'), 'true');
  assert.equal(await input.getAttribute('aria-controls'), 'palette-list');
  assert.equal(await results.getAttribute('tabindex'), '-1', 'the listbox is no Tab stop: the combobox moves through it');
  assert.deepEqual(await active(), { id: 'palette-option-0', selected: 'true', role: 'option', text: 'Round half-cent totals consistently' }, 'the Work Item opened last leads the Recent group');
  assert.deepEqual(await results.getByRole('group').evaluateAll(groups => groups.map(group => group.getAttribute('aria-label'))), ['Recent', 'Commands', 'Go to'], 'commands come before the destinations the sidebar already lists');
  await results.getByRole('group', { name: 'Recent' }).getByRole('option', { name: /^Round half-cent totals consistently\s*Ready for review\s*#105/ }).waitFor();
  await results.getByRole('group', { name: 'Go to' }).getByRole('option', { name: /^Now 9 waiting on you$/ }).waitFor();
  await results.getByRole('group', { name: 'Commands' }).getByRole('option', { name: 'Switch to dark theme' }).waitFor();
  await screenshot('palette-empty');
  await page.keyboard.press('ArrowDown');
  assert.equal((await active()).id, 'palette-option-1');
  await page.keyboard.press('ArrowUp');
  await page.keyboard.press('ArrowUp');
  assert.equal((await active()).id, `palette-option-${await results.getByRole('option').count() - 1}`, 'the arrows wrap around');
  await page.keyboard.press('Home');
  await page.keyboard.press('ArrowDown');
  const before = (await active()).id;
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Close search');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'palette-input', 'Tab stays inside the palette');
  await page.keyboard.press('ArrowDown');
  assert.notEqual((await active()).id, before, 'Tab, Tab, ArrowDown still moves the active option');
  const moved = (await active()).id;
  await results.focus();
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'palette-input', 'an arrow key on the listbox brings focus back to the search field');
  assert.notEqual((await active()).id, moved, 'and moves the active option instead of scrolling');
  await page.keyboard.press('Tab');
  await page.keyboard.type('ins');
  assert.equal(await input.inputValue(), 'ins', 'typing on the Cancel button goes to the search field');
  await first('Insights');
  await page.keyboard.press('Escape');
  await palette.waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Search and commands', 'Escape returns focus to what opened the palette');

  await search('ins', 'Insights');
  assert.equal(await results.locator('#palette-option-0 mark').first().textContent(), 'Ins', 'the matched letters are marked');
  await page.keyboard.press('Enter');
  await palette.waitFor({ state: 'hidden' });
  await page.waitForFunction(() => location.hash === '#insights');

  await page.keyboard.press('/');
  await input.waitFor();
  await input.fill('108');
  await first('Show VAT per line on the order confirmation');
  await screenshot('palette-number');
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => location.hash === '#work/108');
  await page.locator('#page-title').waitFor();

  await search('99999', 'Open Work Item #99999');
  await input.fill('vat line');
  await first('Show VAT per line on the order confirmation');
  await input.fill('zzqxv');
  await palette.getByText('No matches for “zzqxv”').waitFor();
  assert.equal(await results.locator('.empty-state').count(), 0, 'the empty state sits outside the listbox');
  assert.deepEqual(await active(), { id: 'palette-option-0', selected: 'true', role: 'option', text: 'Open Work' }, 'without a match the one next step is active');
  assert.equal(await palette.locator('.palette-hints').isVisible(), false, 'no Move or Open hints without results');
  await page.waitForFunction(() => document.getElementById('palette-status')?.textContent === 'No matches. Enter opens Work.');
  await screenshot('palette-no-results');
  await input.fill('');
  await page.waitForFunction(() => ['Show VAT per line on the order confirmation', 'Round half-cent totals consistently'].includes(document.querySelector('#palette-option-0 .palette-option-label')?.textContent));
  await close();

  await route('settings/preferences');
  await search('dark theme', 'Switch to dark theme');
  await page.keyboard.press('Enter');
  await palette.waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), 'dark');
  await page.waitForFunction(() => document.querySelector('input[data-pref="theme"]:checked')?.value === 'dark');
  await search('system theme', 'Follow the system theme');
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => document.documentElement.dataset.theme === undefined && document.querySelector('input[data-pref="theme"]:checked')?.value === 'system');
  const status = page.locator('.app-topbar').getByRole('group', { name: 'Status' });
  await search('pause live', 'Pause auto-refresh');
  await page.keyboard.press('Enter');
  await status.getByRole('button', { name: 'Resume auto-refresh' }).waitFor();
  assert.equal(await page.evaluate(() => document.querySelector('input[data-pref="live"]')?.checked), false, 'Preferences follows a live-updates change made in the palette');
  await search('resume', 'Resume auto-refresh');
  await page.keyboard.press('Enter');
  await status.getByRole('button', { name: 'Pause auto-refresh' }).waitFor();
  assert.equal(await page.evaluate(() => document.querySelector('input[data-pref="live"]')?.checked), true);
  await search('shortcuts', 'Show keyboard shortcuts');
  await page.keyboard.press('Enter');
  const help = page.getByRole('dialog', { name: 'Keyboard shortcuts' });
  await help.waitFor();
  await screenshot('shortcut-help');
  await page.keyboard.press('Escape');
  await help.waitFor({ state: 'hidden' });
  await page.locator('.app-topbar').getByRole('button', { name: 'Search and commands' }).click();
  await input.fill('single-key');
  await first('Turn off single-key shortcuts');
  await page.keyboard.press('Enter');
  await palette.waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('vloer.prefs')).singleKeyShortcuts), false);
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Search and commands', 'focus returns to the redrawn search button');
  await search('single-key', 'Turn on single-key shortcuts');
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('vloer.prefs')).singleKeyShortcuts === true);
  await search('refresh', 'Refresh this page');
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => document.getElementById('announcement')?.textContent === 'Page refreshed');
  assert.notEqual(await page.evaluate(() => document.activeElement?.tagName), 'BODY', 'refreshing keeps a focused element');

  let failNow = true;
  await page.route('**/api/ploeg/now*', routed => failNow ? routed.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'ploeg_unavailable', message: 'Ploeg did not answer.' } }) }) : routed.continue());
  await page.reload();
  await page.getByRole('heading', { level: 1, name: 'Preferences', exact: true }).waitFor();
  await search('rou');
  await notice.getByText('Work Items could not be loaded. Ploeg did not answer.').waitFor();
  assert.equal(await results.getByRole('option').filter({ hasText: 'could not be loaded' }).count(), 0, 'the failure is a notice, not a result');
  await screenshot('palette-error');
  await input.fill('dark');
  await first('Switch to dark theme');
  assert.equal(await notice.isHidden(), true, 'a query for a command is not told about Work Items');
  await input.fill('rou');
  await notice.waitFor();
  failNow = false;
  await notice.getByRole('button', { name: 'Retry' }).click();
  await first('Round half-cent totals consistently');
  assert.equal(await notice.isHidden(), true, 'a successful retry clears the notice');
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'palette-input', 'retrying keeps focus in the search field');
  await close();
  failNow = true;
  await page.reload();
  await page.getByRole('heading', { level: 1, name: 'Preferences', exact: true }).waitFor();
  await search('rou');
  await notice.waitFor();
  await close();
  failNow = false;
  await route('now');
  assert.equal(await page.evaluate(async () => { const { state } = await import('/core/state.js'); for (let tries = 0; tries < 100 && !state.now.data; tries++) await new Promise(done => setTimeout(done, 50)); return Boolean(state.now.data?.waiting?.length); }), true, 'the Now page loaded');
  for (const query of ['dark', 'help', 'settings', 'rou']) {
    await search(query);
    await page.waitForFunction(() => document.querySelector('#palette-option-0'));
    assert.equal(await notice.isHidden(), true, `the Now page loaded, so '${query}' carries no stale failure`);
    await close();
  }
  await page.unroute('**/api/ploeg/now*');

  await search('notifications', 'Desktop notifications');
  assert.equal(await results.locator('#palette-option-0').getAttribute('aria-disabled'), 'true', 'a browser that blocks notifications gets an explained, disabled row');
  await results.locator('#palette-option-0').getByText('Blocked for this site. Allow notifications in the browser’s site settings.').waitFor();
  await page.keyboard.press('Enter');
  assert.equal(await palette.isVisible(), true, 'a disabled row does nothing');
  await close();
  await page.evaluate(() => {
    window.shownNotifications = [];
    window.RealNotification = window.Notification;
    window.Notification = class { static permission = 'default'; static async requestPermission() { this.permission = 'granted'; return 'granted'; } constructor(title, options) { window.shownNotifications.push({ title, ...options }); } close() {} };
    document.hasFocus = () => false;
  });
  assert.equal(await page.evaluate(async () => { const { state } = await import('/core/state.js'); for (let tries = 0; tries < 100 && !state.now.data; tries++) await new Promise(done => setTimeout(done, 50)); return Boolean(state.now.data?.waiting?.length); }), true, 'the Now page loaded what waits');
  await search('notifications', 'Turn on desktop notifications');
  await page.keyboard.press('Enter');
  await page.locator('#toast').getByText(/^Desktop notifications are on\./).waitFor();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('vloer.prefs')).notify), true, 'the choice is remembered in this browser');
  const sent = await page.evaluate(async () => {
    const { state } = await import('/core/state.js');
    const { applyNowCounts } = await import('/core/counts.js');
    const previous = state.now.data;
    const next = { ...previous, waiting: [...previous.waiting, { id: '990', team: 'delivery', state: 'needs_human', title: 'A new item that needs you', updatedAt: new Date().toISOString(), closeReason: 'plan_exhausted', latestShift: { closeReason: 'plan_exhausted', closedAt: new Date().toISOString() } }] };
    state.now.data = next;
    applyNowCounts(next);
    const empty = { ...previous, waiting: [] };
    state.now.data = empty;
    applyNowCounts(empty);
    const plain = document.querySelector('link[rel~="icon"]').getAttribute('href');
    state.now.data = previous;
    applyNowCounts(previous);
    return { shown: window.shownNotifications, plain };
  });
  assert.deepEqual(sent.shown.map(item => [item.title, item.tag]), [['A new item that needs you', 'vloer-waiting-990']], 'one notification for the item that started waiting');
  assert.equal(sent.plain, '/favicon.svg', 'the plain favicon returns when nothing waits');
  assert.match(await favicon(), /^data:image\/png;base64,/);
  await search('notifications', 'Turn off desktop notifications');
  await page.keyboard.press('Enter');
  await page.locator('#toast').getByText('Desktop notifications are off.').waitFor();
  await page.evaluate(() => { window.Notification = window.RealNotification; delete document.hasFocus; });

  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.app-topbar').getByRole('button', { name: 'Search and commands' }).click();
  await input.waitFor();
  const sheet = await palette.boundingBox();
  assert.deepEqual([Math.round(sheet.x), Math.round(sheet.width)], [0, 390], 'the palette is a full-width sheet on phones');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth || document.getElementById('palette').scrollWidth > document.getElementById('palette').clientWidth), false, 'the phone palette overflows horizontally');
  const cancel = palette.getByRole('button', { name: 'Close search' });
  assert((await cancel.boundingBox()).height >= 44, 'the phone close button is at least 44 px tall');
  await screenshot('palette-390');
  await cancel.click();
  await palette.waitFor({ state: 'hidden' });
  await page.locator('.app-topbar').getByRole('button', { name: 'Search and commands' }).click();
  await input.fill('runs');
  await results.getByRole('option', { name: /^Runs/ }).first().click();
  await page.waitForFunction(() => location.hash === '#runs');
  assert.equal(await hash(), '#runs');
  await page.setViewportSize({ width: 1440, height: 1040 });

  const liveBase = `http://127.0.0.1:${live.server.address().port}`;
  const signIn = async () => {
    await page.getByRole('textbox', { name: 'Account name' }).fill('browser-operator');
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await page.locator('#page-title').waitFor();
  };
  const secret = { kind: 'work', id: '4242', title: 'Confidential acquisition of Acme', at: new Date().toISOString() };
  await page.goto(`${liveBase}/#settings/accounts`);
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  await page.evaluate(entry => localStorage.setItem('vloer.recent', JSON.stringify([entry])), secret);
  await signIn();
  await search('');
  assert.equal(await palette.getByText(secret.title).count(), 0, 'a recent list without an owner is never shown');
  assert.equal(await page.evaluate(() => localStorage.getItem('vloer.recent')), null, 'and it is dropped from this browser');
  await close();
  await page.evaluate(entry => localStorage.setItem('vloer.recent', JSON.stringify({ user: 'someone-else', entries: [entry] })), secret);
  await search('');
  assert.equal(await palette.getByText(secret.title).count(), 0, 'another account’s recent Work Items stay hidden');
  assert.equal(await page.evaluate(() => localStorage.getItem('vloer.recent')), null, 'and are dropped from this browser');
  await close();
  await route('work/4242');
  await route('settings/accounts');
  await search('');
  await results.getByRole('group', { name: 'Recent' }).getByRole('option', { name: /^Work Item #4242/ }).waitFor();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('vloer.recent')).user === 'someone-else'), false, 'the list now belongs to this account');
  await input.fill('sign out');
  await first('Sign out');
  await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  await signIn();
  await search('');
  await results.getByRole('group', { name: 'Recent' }).getByRole('option', { name: /^Work Item #4242/ }).waitFor();
  await input.fill('sign out');
  await first('Sign out');
  await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  await page.goto(`${base}/#runs`);
  await page.getByRole('heading', { level: 1, name: 'Runs', exact: true }).waitFor();
}
