/** The workbench chrome: redirects from old links, focus, title and announcement on route changes, the status strip, the account menu with the theme switch, live updates, keyboard shortcuts, opening and closing the command palette, the skip link, and the drawer, bottom bar and home link at phone width. */
export async function run({ page, app, assert, screenshot }) {
  const base = `http://127.0.0.1:${app.server.address().port}`;
  const hash = () => page.evaluate(() => location.hash);
  await page.setViewportSize({ width: 1440, height: 1040 });
  for (const [from, to, heading] of [['#ploeg/lane/needs_human', '#work?lane=needs_human', 'Work'], ['#ploeg/105', '#work/105', 'Work'], ['#ploeg', '#insights', 'Insights'], ['#ploeg/runs', '#runs', 'Runs'], ['#account', '#settings/accounts', 'Linked accounts'], ['#system', '#settings/environment', 'Environment'], ['#compare/a/b', '#sessions', 'Sessions']]) {
    await page.goto(`${base}/${from}`);
    await page.getByRole('heading', { level: 1, name: heading, exact: true }).waitFor();
    assert.equal(await hash(), to, `${from} did not redirect to ${to}`);
  }
  const historyLength = await page.evaluate(() => history.length);
  await page.evaluate(() => { location.hash = 'ploeg/activity'; });
  await page.waitForFunction(() => location.hash === '#activity');
  assert.equal(await page.evaluate(() => history.length), historyLength + 1, 'a redirect replaces the old entry instead of adding one');
  await page.getByRole('heading', { level: 1, name: 'Activity', exact: true }).waitFor();
  await page.waitForFunction(() => document.activeElement?.id === 'page-title');
  assert.match(await page.title(), /^\(\d+\) Activity · De Vloer$/, 'the title leads with what waits on you');
  assert.equal(await page.locator('#announcement').textContent(), 'Activity');
  const status = page.locator('.app-topbar').getByRole('group', { name: 'Status' });
  await status.getByText('Ploeg: demo data', { exact: true }).waitFor();
  await status.getByText('Demo', { exact: true }).waitFor();
  await status.getByText(/^Updated /).waitFor();
  const liveToggle = status.getByRole('button', { name: 'Updates: Live' });
  await liveToggle.click();
  await status.getByRole('button', { name: 'Updates: Paused' }).waitFor();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('vloer.prefs')).live), false, 'pausing is remembered');
  await status.getByRole('button', { name: 'Updates: Paused' }).click();
  await liveToggle.waitFor();
  const account = page.getByRole('button', { name: /^Account and theme/ });
  await account.click();
  assert.equal(await account.getAttribute('aria-expanded'), 'true');
  await page.getByRole('group', { name: 'Theme' }).getByRole('button', { name: 'Dark' }).click();
  assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), 'dark');
  assert.equal(await page.getByRole('group', { name: 'Theme' }).getByRole('button', { name: 'Dark' }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('group', { name: 'Theme' }).getByRole('button', { name: 'System' }).click();
  assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), undefined);
  await page.keyboard.press('Escape');
  assert.equal(await account.getAttribute('aria-expanded'), 'false');
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')?.startsWith('Account and theme')), true, 'Escape returns focus to the account button');
  await page.keyboard.press('?');
  const help = page.getByRole('dialog', { name: 'Keyboard shortcuts' });
  await help.getByText('Search and commands').first().waitFor();
  await page.keyboard.press('Escape');
  await help.waitFor({ state: 'hidden' });
  await page.keyboard.press('g');
  await page.keyboard.press('w');
  await page.waitForFunction(() => location.hash === '#work');
  await page.getByRole('heading', { level: 1, name: 'Work', exact: true }).waitFor();
  await page.keyboard.press('/');
  const palette = page.getByRole('dialog', { name: 'Search and commands' });
  await palette.getByRole('combobox', { name: 'Search pages, commands and Work Items' }).waitFor();
  await page.keyboard.press('Escape');
  await palette.waitFor({ state: 'hidden' });
  await page.keyboard.press('Control+k');
  await palette.waitFor();
  await palette.getByRole('button', { name: 'Close search' }).click();
  await palette.waitFor({ state: 'hidden' });
  await status.getByText(/^Updated /).waitFor();
  await page.evaluate(() => { location.hash = 'settings/preferences'; });
  await page.getByRole('heading', { level: 1, name: 'Preferences', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => [...document.querySelectorAll('[data-live-updated]')].every(element => element.hidden && !element.textContent)), true, 'a page that loads nothing live must not claim to be fresh');
  const before = await hash();
  await page.locator('.skip-link').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'main', 'the skip link moves focus to the main content');
  assert.equal(await hash(), before, 'the skip link must not change the route');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Open navigation' }).first().click();
  const drawer = page.getByRole('dialog', { name: 'Navigation' });
  await drawer.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: 'Insights', exact: true }).waitFor();
  await drawer.getByRole('group', { name: 'Theme' }).waitFor();
  await screenshot('navigation-drawer-390');
  await page.keyboard.press('Escape');
  await drawer.waitFor({ state: 'hidden' });
  await page.getByRole('navigation', { name: 'Quick navigation' }).getByRole('button', { name: 'More' }).click();
  await drawer.getByRole('link', { name: 'Runs', exact: true }).click();
  await drawer.waitFor({ state: 'hidden' });
  await page.getByRole('heading', { level: 1, name: 'Runs', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile Runs layout overflows horizontally');
  await page.getByRole('link', { name: 'De Vloer home' }).click();
  await page.locator('.now-group').first().waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile Now layout overflows horizontally');
  await screenshot('mobile');
}
