import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readBacklog, validateBacklog } from './backlog.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const output = resolve(root, 'docs/PRODUCT-DESIGN.md');
const chapters = [
  ['Product and system design', 'docs/design/00-product-system-design.md'],
  ['Self-improvement and dogfooding', 'docs/design/self-improvement.md'],
  ['Code audit and gap register', 'docs/design/gap-register.md'],
  ['Tickets, work orders and delivery', 'docs/design/ticket-integration.md'],
  ['Platform and governance', 'docs/design/platform-and-governance.md'],
  ['IDE and operator experience', 'docs/design/ide-and-operator-experience.md'],
  ['Market landscape and alternatives', 'docs/research/market-landscape.md'],
  ['Positioning and go-to-market', 'docs/product/go-to-market.md'],
  ['From design to tracker and agent work', 'docs/operations/backlog.md']
];
function localTarget(from, target) {
  if (/^(?:[a-z][a-z\d+.-]*:|\/\/)/i.test(target)) return null;
  const [file] = target.split(/[?#]/);
  return file ? resolve(dirname(from), file) : from;
}
function transform(source, from, mapper) {
  let fence = null;
  return source.split('\n').map(line => {
    const delimiter = line.match(/^\s*(`{3,}|~{3,})/);
    if (delimiter) {
      if (fence && delimiter[1][0] === fence[0] && delimiter[1].length >= fence.length) fence = null;
      else if (!fence) fence = delimiter[1];
      return line;
    }
    return fence ? line : mapper(line, from);
  }).join('\n');
}
const backlog = readBacklog();
validateBacklog(backlog);
const content = [
  '# Product design: chapter guide',
  '',
  'Generated by `npm run design:build` from the chapter list in [the builder](../scripts/build-design.mjs). Read the source chapters directly; this guide avoids maintaining a second copy of their prose.',
  '',
  '## Current behavior',
  '',
  'Start with [the documentation index](index.md), [architecture](architecture.md) and [shared execution contract](contracts/ploeg-execution.md). Current setup is in [the unified guide](operations/unified-baseline.md).',
  '',
  '## Design and research baseline',
  '',
  'The design chapters began on 9 September 2026. They mix product proposals, commercial hypotheses and gaps found in the original implementation. Later implementation notes do not revalidate every earlier claim. Check current contracts and source before treating a gap as still open. Local Vloer work must remain usable without Ploeg. The engines remain separate; [open product choices](../../../docs/landscape/questions.md) are tracked explicitly.',
  '',
  ...chapters.map(([title, path]) => `- [${title}](${relative(dirname(output), resolve(root, path))})`),
  '',
  '## Structured sources and decisions',
  '',
  '- [Backlog JSON](../backlog/backlog.json) generates [the readable backlog](../backlog/README.md). Its '+backlog.tickets.length+' records are planning data, not execution grants or proof of completed features.',
  '- [Domain YAML](../../../docs/domain/model.yaml) generates the [glossary](../../../docs/domain/glossary.md) and [rules](../../../docs/domain/rules.md). Product intentions and open choices are marked explicitly.',
  '- [ADR index](adrs/README.md) records decisions and their status.',
  '- [Market source ledger](research/market-sources.json) retains research provenance.',
  '- [Proposed WorkOrder schema](contracts/work-order.v1.schema.json) and [event envelope](contracts/event-envelope.v1.schema.json) describe proposed interfaces; use [the HTTP API](contracts/api.md) for implemented requests.',
  '',
  '## History and maintenance',
  '',
  'The [former compiled edition](https://forgejo.webgrip.dev/webgrip/de-vloer/src/commit/7c8657e15b1525e30641b12e5175bf268a49b03d/docs/PRODUCT-DESIGN.md) remains in Git. Its contents are also retained in the source chapters. The [documentation audit](research/2026-09-12-documentation-audit.md) explains the consolidation.',
  '',
  '`npm run design:check` checks this generated guide and local links in its source chapters. It does not validate proposed features or market claims.',
  ''
].join('\n');
const failures = [];
for (const [path, source] of [...chapters.map(([, path]) => [resolve(root, path), readFileSync(resolve(root, path), 'utf8')]), [output, content]]) {
  transform(source, path, (line, from) => {
    for (const match of line.matchAll(/!?\[[^\]\n]*\]\(([^\s)]+)\)/g)) {
      const target = localTarget(from, match[1]);
      if (target && target !== output && !existsSync(target)) failures.push(`${relative(root, from)}: missing ${match[1]}`);
    }
    return line;
  });
}
if (process.argv.includes('--check')) {
  if (!existsSync(output) || readFileSync(output, 'utf8') !== content) failures.push('docs/PRODUCT-DESIGN.md is stale; run npm run design:build');
} else if (!failures.length) writeFileSync(output, content);
if (failures.length) {
  process.stderr.write(failures.join('\n') + '\n'); process.exitCode = 1;
} else process.stdout.write(`${process.argv.includes('--check') ? 'Checked' : 'Built'} design chapter guide: ${content.split(/\s+/).filter(Boolean).length.toLocaleString('en-US')} words, ${chapters.length} source chapters, ${backlog.tickets.length} tickets; local links resolve.\n`);
