#!/usr/bin/env python3
import json
import os
import sys

registry = sys.stdin.read().strip().removeprefix('https://').rstrip('/')
credentials = {
    'harbor.webgrip.dev': ('HARBOR_ROBOT_USER', 'HARBOR_ROBOT_TOKEN'),
    'ghcr.io': ('GHCR_USERNAME', 'GHCR_TOKEN'),
    'forgejo.webgrip.dev': ('', 'WEBGRIP_CI_TOKEN'),
}
if sys.argv[1:] != ['get'] or registry not in credentials:
    sys.exit(1)
user, token = credentials[registry]
print(json.dumps({'Username': os.environ[user] if user else 'webgrip-ci', 'Secret': os.environ[token]}))
