import argparse
import os
import re
import sys
from pathlib import Path
from urllib.parse import quote

import yaml

root = Path(__file__).resolve().parent.parent
LEDGERS = [('system', 'System', 'docs/adr'), ('ploeg', 'Ploeg', 'apps/ploeg/docs/adrs'), ('vloer', 'Vloer', 'apps/vloer/docs/adrs')]
OUTPUT = 'docs/reference/decisions.md'
EVIDENCE = 'docs/reference/decisions-implementation.yaml'
COMMAND = 'mise run docs-decisions'
RECORD = re.compile(r'^(?:adr-)?(\d{4})-[a-z0-9][a-z0-9._-]*\.md$')
REFERENCE = re.compile(r'(?:(system|ploeg|vloer)[:/ ]+)?(?:ADR-?)?(\d{4})', re.I)


def parse(path):
    """Return number, title, status, primary status, date and supersedes references of one ADR file."""
    text = path.read_text()
    front = re.match(r'\A---\n(.*?)\n---\n', text, re.S)
    meta = yaml.safe_load(front[1]) if front else {}
    body = text[front.end():] if front else text
    title = re.search(r'^# (.+)$', body, re.M)[1].strip()
    title = re.sub(r'^(?:ADR-?)?\d{4}\s*[—–:-]\s*', '', title)
    if meta and 'status' in meta:
        status, date = str(meta['status']), str(meta.get('date', ''))
    else:
        inline = re.search(r'^(?:Date:\s*(\d{4}-\d{2}-\d{2})\.\s*)?Status:\s*(.+?)\s*$', body, re.M)
        status, date = (inline[2].rstrip('.'), inline[1] or '') if inline else ('', '')
    word = re.match(r'[a-z]+', re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', status).lower())
    raw = (meta or {}).get('supersedes') or ''
    values = raw if isinstance(raw, list) else [raw]
    supersedes = ' '.join(f'{value:04d}' if isinstance(value, int) else str(value) for value in values)
    return {
        'number': RECORD.match(path.name)[1],
        'file': path,
        'title': title,
        'status': status,
        'primary': word[0] if word else '',
        'date': date,
        'supersedes': [] if supersedes.lower().startswith('none') else REFERENCE.findall(supersedes),
    }


def collect(base=root):
    records = []
    for scope, label, folder in LEDGERS:
        for path in sorted((base / folder).glob('*.md')):
            if RECORD.match(path.name) and not path.name.startswith(('adr-0000', '0000')) and 'template' not in path.name:
                records.append({'scope': scope, 'label': label, **parse(path)})
    index = {(record['scope'], record['number']): record for record in records}
    for record in records:
        record.setdefault('superseded_by', [])
    for record in records:
        references = list(record['supersedes'])
        if record['primary'] == 'superseded':
            continue
        for scope, number in references:
            target = index.get(((scope or record['scope']).lower(), number))
            if target:
                target['superseded_by'].append(record)
    for record in records:
        if record['primary'] == 'superseded':
            for scope, number in REFERENCE.findall(record['status']):
                target = index.get(((scope or record['scope']).lower(), number))
                if target and target not in record['superseded_by']:
                    record['superseded_by'].append(target)
    return records


def link(record, output):
    return f"[{record['number']}]({quote(os.path.relpath(record['file'], output.parent))})"


def reference(record, output):
    return f"{record['label']} {link(record, output)}"


def cell(text):
    return text.replace('|', '\\|').replace('\n', ' ')


def render(base=root):
    output = base / OUTPUT
    records = collect(base)
    evidence_path = base / EVIDENCE
    evidence = yaml.safe_load(evidence_path.read_text()) if evidence_path.exists() else {}
    checked = evidence.get('checked', 'an unrecorded date') if evidence else 'an unrecorded date'
    lines = [
        '---',
        'type: reference',
        'audience: [owner, contributor, agent]',
        'owner: glide',
        f'generated_by: "{COMMAND}"',
        '---',
        '',
        '# Decision register',
        '',
        f'*Generated by `scripts/docs-decisions.py` from the three ADR ledgers and `{EVIDENCE}`. Do not edit by hand; regenerate with `{COMMAND}`.*',
        '',
        'This page lists every architecture decision record in Glide\'s three ledgers: [system](../adr/index.md), [Ploeg](../../apps/ploeg/docs/adrs/README.md) and [Vloer](../../apps/vloer/docs/adrs/README.md). Each ledger stays the source; this page is regenerated from them and fails `mise run docs-check` when it drifts.',
        '',
        'An accepted record states why a rule exists. A proposed record is an open question, even when code already implements it.',
        '',
        '## Accepted',
        '',
        '| Scope | ADR | Title | Date | Superseded by |',
        '| --- | --- | --- | --- | --- |',
    ]
    order = {'system': 0, 'ploeg': 1, 'vloer': 2}
    key = lambda record: (order[record['scope']], record['number'])
    for record in sorted((r for r in records if r['primary'] == 'accepted'), key=key):
        replaced = ', '.join(reference(other, output) for other in record['superseded_by']) or '—'
        lines.append(f"| {record['label']} | {link(record, output)} | {cell(record['title'])} | {record['date']} | {replaced} |")
    lines += [
        '',
        '## Proposed',
        '',
        f'"Implemented?" records whether the ADR text or code showed the decision in place when it was last checked ({checked}). It says nothing about ratification. "unknown" means nobody has checked. Update [the evidence file]({quote(os.path.relpath(evidence_path, output.parent))}) and regenerate when that changes.',
        '',
        '| Scope | ADR | Title | Date | Implemented? | Evidence |',
        '| --- | --- | --- | --- | --- | --- |',
    ]
    for record in sorted((r for r in records if r['primary'] == 'proposed'), key=key):
        entry = (evidence or {}).get(record['scope'], {}).get(record['number']) or {}
        verdict = str(entry.get('implemented', 'unknown'))
        proof = cell(entry.get('note', '')) if entry else ''
        if entry.get('evidence'):
            target = base / entry['evidence']
            proof = (proof + ' ' if proof else '') + f"([source]({quote(os.path.relpath(target, output.parent))}))"
        lines.append(f"| {record['label']} | {link(record, output)} | {cell(record['title'])} | {record['date']} | {verdict} | {proof or '—'} |")
    rest = sorted((r for r in records if r['primary'] not in {'accepted', 'proposed'}), key=key)
    lines += ['', '## Other statuses', '']
    if rest:
        lines += ['| Scope | ADR | Title | Status | Date | Superseded by |', '| --- | --- | --- | --- | --- | --- |']
        for record in rest:
            replaced = ', '.join(reference(other, output) for other in record['superseded_by']) or '—'
            lines.append(f"| {record['label']} | {link(record, output)} | {cell(record['title'])} | {cell(record['status'])} | {record['date']} | {replaced} |")
    else:
        lines.append('No record is rejected, deprecated or superseded.')
    return '\n'.join(lines) + '\n'


def unknown_evidence(base=root):
    """Return evidence entries that name no proposed record or no existing file."""
    evidence_path = base / EVIDENCE
    evidence = yaml.safe_load(evidence_path.read_text()) if evidence_path.exists() else {}
    proposed = {(r['scope'], r['number']) for r in collect(base) if r['primary'] == 'proposed'}
    problems = []
    for scope, entries in (evidence or {}).items():
        if scope == 'checked':
            continue
        for number, entry in (entries or {}).items():
            if (scope, str(number)) not in proposed:
                problems.append(f'{scope} {number}: not a proposed record')
            if entry.get('implemented') not in {'yes', 'partial', 'no'}:
                problems.append(f'{scope} {number}: implemented must be yes, partial or no')
            if entry.get('evidence') and not (base / entry['evidence']).exists():
                problems.append(f"{scope} {number}: missing evidence {entry['evidence']}")
    return problems


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate the cross-ledger decision register.')
    parser.add_argument('--check', action='store_true', help='fail when the committed register is stale')
    args = parser.parse_args()
    problems = unknown_evidence()
    if problems:
        sys.exit('Decision evidence problems:\n' + '\n'.join(problems))
    expected = render()
    target = root / OUTPUT
    if args.check:
        if not target.exists() or target.read_text() != expected:
            sys.exit(f'Stale decision register: {OUTPUT}; regenerate with `{COMMAND}`')
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected)
        print(f'Wrote {OUTPUT}')
