/** Live sign-in and sign-out against the live-mode server, whose bootstrap account uses `password`: a failed attempt that keeps the account name, the phone layout, a session that expires mid-use, and a sign-out after which the next person never sees the previous person's Now page. */
export async function run({ page, live, password, assert, screenshot }) {
  const signIn = async () => {
    await page.getByRole('textbox', { name: 'Account name' }).fill('browser-operator');
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  };
  await page.goto(`http://127.0.0.1:${live.server.address().port}`);
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  await screenshot('login');
  const reveal = page.getByRole('button', { name: 'Show password', exact: true });
  await page.getByLabel('Password', { exact: true }).fill('visible');
  await reveal.click();
  assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'text', 'Show password did not show it');
  assert.equal(await reveal.getAttribute('aria-pressed'), 'true');
  await reveal.click();
  assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'password');
  assert.equal(await reveal.getAttribute('aria-pressed'), 'false');
  await page.getByRole('textbox', { name: 'Account name' }).fill('browser-operator');
  await page.getByLabel('Password', { exact: true }).fill('not-the-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByText('Name or password is incorrect.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('textbox', { name: 'Account name' }).inputValue(), 'browser-operator', 'a failed sign-in cleared the account name');
  assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('aria-invalid'), 'true');
  assert.equal(await page.evaluate(() => document.activeElement?.id), 'login-password', 'a failed sign-in does not return to the password');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'the sign-in page overflows at 390px');
  await screenshot('login-error-390');
  await page.setViewportSize({ width: 1440, height: 1040 });
  await signIn();
  await page.getByRole('heading', { name: 'Now', exact: true }).first().waitFor();
  await page.keyboard.press('?');
  await page.getByRole('dialog', { name: 'Keyboard shortcuts' }).waitFor();
  await page.context().clearCookies();
  await page.evaluate(() => { location.hash = 'settings/accounts'; });
  await page.getByText('Your session expired', { exact: true }).waitFor();
  await page.getByText('Sign in again to continue where you were.', { exact: true }).waitFor();
  assert.equal(await page.locator('dialog[open]').count(), 0, 'a dialog stayed open over the sign-in page');
  assert.equal(await page.title(), 'Sign in · Unfold', 'the sign-in page keeps the title of the page it replaced');
  assert.equal(new URL(page.url()).hash, '#settings/accounts');
  await signIn();
  await page.getByRole('heading', { level: 1, name: 'Linked accounts', exact: true }).waitFor();
  await page.route('**/api/health', route => route.fulfill({ status: 503, json: { error: { code: 'unavailable', message: 'The workbench did not answer.' } } }));
  await page.getByRole('link', { name: 'Environment', exact: true }).click();
  const gateway = page.locator('.health-check', { has: page.getByRole('heading', { name: 'Model gateway', exact: true }) });
  await gateway.getByText('Unknown', { exact: true }).waitFor();
  await page.unroute('**/api/health');
  await page.context().clearCookies();
  await gateway.getByRole('button', { name: 'Check again', exact: true }).click();
  await page.getByText('Your session expired', { exact: true }).waitFor();
  assert.equal(await page.locator('#toast').evaluate(toast => toast.textContent.includes('Cannot read')), false, 'an expired session on Environment showed a script error');
  await signIn();
  await page.getByRole('heading', { level: 1, name: 'Environment', exact: true }).waitFor();
  await page.getByRole('link', { name: 'Linked accounts', exact: true }).click();
  await page.getByRole('heading', { level: 1, name: 'Linked accounts', exact: true }).waitFor();
  await page.getByRole('button', { name: /^Account and theme/ }).click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  assert.equal(await page.getByText('Your session expired', { exact: false }).count(), 0, 'signing out on purpose is not an expired session');
  assert.equal(await page.getByRole('textbox', { name: 'Account name' }).inputValue(), '', 'signing out kept the last account name');
  const at = new Date().toISOString();
  const secret = { demo: false, fetchedAt: at, errors: {}, running: [], recent: [], waiting: [{ id: '901', team: 'delivery', state: 'needs_human', title: 'SECRET-A Confidential acquisition', url: '', createdAt: at, updatedAt: at, provider: 'vikunja', externalId: 'VIK-901', attempts: 1, infraFailures: 0, target: null, closeReason: 'plan_exhausted', latestShift: null, spentUsd: null, pullRequestUrl: '' }] };
  let nowAnswer = { status: 200, json: secret };
  await page.route('**/api/ploeg/now*', route => route.fulfill(nowAnswer));
  await page.evaluate(() => { location.hash = 'now'; });
  await signIn();
  await page.getByText('SECRET-A Confidential acquisition', { exact: true }).first().waitFor();
  await page.getByRole('button', { name: /^Account and theme/ }).click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  nowAnswer = { status: 503, json: { error: { code: 'ploeg_unavailable', message: 'Ploeg did not answer.' } } };
  await signIn();
  await page.getByText('Could not reach Ploeg', { exact: true }).waitFor();
  assert.equal(await page.getByText('SECRET-A', { exact: false }).count(), 0, 'the next person to sign in saw the previous person’s Now page');
  assert.equal(await page.title(), 'Now · Unfold', 'the previous person’s waiting count stayed in the tab title');
  await page.unroute('**/api/ploeg/now*');
  await page.getByRole('button', { name: /^Account and theme/ }).click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
}
