import { navigate } from './navigate.mjs';

/** Settings: the Environment health checks, one content width on every Settings page, Preferences for theme, density, single-key shortcuts and live updates, kept across a reload and in step with the top bar and account menu, the style guide's preview that leaving restores, and Connect VS Code from the account menu with its install links and a manual address minted only on click. */
export async function run({ page, assert, screenshot }) {
  const root = name => page.evaluate(attribute => document.documentElement.getAttribute(attribute), name);
  const pageWidth = () => page.locator('.settings-page').evaluate(element => element.getBoundingClientRect().width);
  await navigate(page, 'Settings');
  await page.getByRole('link', { name: 'Environment', exact: true }).click();
  await page.getByRole('heading', { name: 'Health checks', exact: true }).waitFor();
  const ploegCheck = page.locator('.health-check', { has: page.getByRole('heading', { name: 'Ploeg connection', exact: true }) });
  await ploegCheck.getByText('Demo data', { exact: true }).waitFor();
  assert.equal(await page.locator('.health-check').count(), 6, 'the Environment page does not list every health check');
  const runtimeCheck = page.locator('.health-check', { has: page.getByRole('heading', { name: 'Agent runtimes', exact: true }) });
  await runtimeCheck.getByText('Registered', { exact: true }).waitFor();
  await screenshot('environment');
  const environmentWidth = await pageWidth();
  await page.getByRole('link', { name: 'Linked accounts', exact: true }).click();
  await page.getByRole('heading', { level: 1, name: 'Linked accounts', exact: true }).waitFor();
  assert.equal(await pageWidth(), environmentWidth, 'Linked accounts and Environment use different content widths');
  await page.getByRole('link', { name: 'Preferences', exact: true }).click();
  await page.getByRole('heading', { level: 1, name: 'Preferences', exact: true }).waitFor();
  assert.equal(await pageWidth(), environmentWidth, 'Preferences and Environment use different content widths');
  await page.getByRole('radio', { name: /^Dark/ }).check();
  assert.equal(await root('data-theme'), 'dark');
  await page.getByRole('radio', { name: /^Compact/ }).check();
  assert.equal(await root('data-density'), 'compact');
  await page.reload();
  await page.getByRole('heading', { level: 1, name: 'Preferences', exact: true }).waitFor();
  assert.equal(await root('data-theme'), 'dark', 'the theme did not survive a reload');
  assert.equal(await page.getByRole('radio', { name: /^Dark/ }).isChecked(), true);
  await screenshot('preferences-dark');
  await page.getByRole('switch', { name: 'Refresh automatically', exact: true }).uncheck();
  assert.equal(await page.locator('.app-topbar [data-live-toggle]').getAttribute('aria-label'), 'Resume auto-refresh', 'the live updates switch and the top bar disagree');
  await page.getByRole('switch', { name: 'Refresh automatically', exact: true }).check();
  assert.equal(await page.locator('.app-topbar [data-live-toggle]').getAttribute('aria-label'), 'Pause auto-refresh');
  await page.getByRole('switch', { name: 'Single-key shortcuts', exact: true }).uncheck();
  await page.locator('#page-title').focus();
  await page.keyboard.press('?');
  assert.equal(await page.locator('#shortcuts').evaluate(dialog => dialog.open), false, 'a single-key shortcut ran while switched off');
  await page.keyboard.press('Control+k');
  await page.getByRole('dialog', { name: 'Search and commands' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('switch', { name: 'Single-key shortcuts', exact: true }).check();
  const viewport = page.viewportSize();
  await page.setViewportSize({ width: 1440, height: 1040 });
  await page.locator('.app-topbar [data-live-toggle]').click();
  assert.equal(await page.getByRole('switch', { name: 'Refresh automatically', exact: true }).isChecked(), false, 'the pause button in the top bar left the Preferences switch on');
  await page.locator('.app-topbar [data-live-toggle]').click();
  assert.equal(await page.getByRole('switch', { name: 'Refresh automatically', exact: true }).isChecked(), true);
  await page.getByRole('button', { name: /^Account and theme/ }).click();
  await page.locator('.app-user-menu [data-action="theme-set"][data-value="light"]').click();
  assert.equal(await page.getByRole('radio', { name: /^Light/ }).isChecked(), true, 'the account menu theme left the Preferences tiles on the old theme');
  assert.equal(await page.locator('.app-user-menu').isVisible(), true, 'changing the theme from the account menu closed it');
  await page.keyboard.press('Escape');
  await page.setViewportSize(viewport);
  await page.getByRole('radio', { name: /^System/ }).check();
  await page.getByRole('radio', { name: /^Comfortable/ }).check();
  assert.equal(await root('data-theme'), null);
  assert.equal(await root('data-density'), null);
  await page.getByRole('link', { name: 'living style guide' }).click();
  await page.getByRole('heading', { level: 1, name: 'Design system', exact: true }).waitFor();
  await page.getByRole('group', { name: 'Preview theme' }).getByRole('button', { name: 'Dark', exact: true }).click();
  await page.getByRole('group', { name: 'Preview density' }).getByRole('button', { name: 'Compact', exact: true }).click();
  assert.deepEqual([await root('data-theme'), await root('data-density')], ['dark', 'compact'], 'the style guide preview did not apply');
  await page.evaluate(() => { location.hash = 'settings/preferences'; });
  await page.getByRole('heading', { level: 1, name: 'Preferences', exact: true }).waitFor();
  assert.deepEqual([await root('data-theme'), await root('data-density')], [null, null], 'leaving the style guide kept its preview instead of the saved preference');

  await page.getByRole('button', { name: /^Account and theme/ }).click();
  await page.locator('.app-user-menu').getByRole('link', { name: 'Connect VS Code', exact: true }).click();
  const connectCard = page.locator('section.card', { has: page.getByRole('heading', { level: 2, name: 'Connect VS Code', exact: true }) });
  await connectCard.waitFor();
  assert.equal(await pageWidth(), environmentWidth, 'Signed-in editors and Environment use different content widths');
  const origin = await page.evaluate(() => location.origin);
  assert.equal(await connectCard.getByRole('link', { name: 'Connect VS Code', exact: true }).getAttribute('href'), `vscode://webgrip.unfold/connect-agents-window?origin=${encodeURIComponent(origin)}`);
  await connectCard.getByText('No Unfold extension in VS Code?', { exact: true }).click();
  assert.equal(await connectCard.getByRole('link', { name: 'Open VSX' }).getAttribute('href'), 'https://open-vsx.org/extension/webgrip/unfold');
  assert.equal(await connectCard.getByRole('link', { name: 'the Extensions view in VS Code' }).getAttribute('href'), 'vscode:extension/webgrip.unfold');
  await connectCard.getByText('Sessions: Add Remote Agent Host…', { exact: true }).waitFor();
  assert.equal(await page.locator('#vscode-connect-address').count(), 0, 'no token is minted or shown before the click');
  await page.evaluate(() => { navigator.clipboard.writeText = () => Promise.reject(new Error('denied')); });
  await connectCard.getByRole('button', { name: 'Copy address', exact: true }).click();
  const address = await page.locator('#vscode-connect-address').inputValue();
  assert.match(address, /^wss?:\/\/[^/]+\/\?tkn=[0-9A-Za-z_-]{16,128}$/, 'a refused clipboard shows the address to copy by hand');
  await screenshot('connect-vscode');
}
