import type { PloegDetail, PloegItem, PloegRun, PloegShift, PloegTeam } from './ploeg.ts';

const at = '2026-09-10T09:00:00Z';
const teams: PloegTeam[] = [{ id: 'delivery', paused: null, queueDepth: 1, roles: [{ id: 'implementer', queueDepth: 1 }, { id: 'reviewer', queueDepth: 0 }] }, { id: 'research', paused: null, queueDepth: 1, roles: [{ id: 'analyst', queueDepth: 1 }] }];
const shift: PloegShift = { id: '11', workItemId: '101', team: 'delivery', branch: 'demo/rounding-review', round: 1, budgetUsd: 0, spentUsd: 0, reservedUsd: 0, openedAt: at, closedAt: at, closeReason: 'Illustrative escalation to a human reviewer.' };
const base = { provider: 'demo', description: 'Illustrative work item for exploring the operator workbench. No dispatch or model calls occurred.', externalId: '', revision: 'illustrative-v1', team: 'delivery', priority: 1, attempts: 0, infraFailures: 0, nextEligibleAt: null, createdAt: at, updatedAt: at, target: { forge: 'demo', owner: 'example', repo: 'order-service', baseBranch: 'main' }, lease: null, latestShift: null, url: '' };
const items: PloegItem[] = [
  { ...base, id: '101', externalId: 'DEMO-1', title: 'Review the rounding acceptance criteria', state: 'needs_human', attempts: 1, latestShift: shift },
  { ...base, id: '102', externalId: 'DEMO-2', title: 'Prepare a regression investigation', state: 'leased', attempts: 1, latestShift: { ...shift, id: '12', workItemId: '102', closedAt: null, closeReason: '', branch: 'demo/regression-investigation' }, lease: { renewedAt: at, expiresAt: '2026-09-10T09:30:00Z' } },
  { ...base, id: '103', externalId: 'DEMO-3', title: 'Document the order verification workflow', state: 'queued' },
  { ...base, id: '104', externalId: 'DEMO-4', title: 'Define evidence for a market research brief', state: 'queued', team: 'research', target: null },
];
const run: PloegRun = { id: '21', workItemId: '101', shiftId: '11', team: 'delivery', role: 'reviewer', round: 1, writes: false, state: 'finished', startedAt: at, finishedAt: at, expiresAt: null, outcome: 'stuck', summary: 'Illustrative reviewer handoff: agree on the rounding rule before changing the implementation.', stuckReason: 'The acceptance criteria need a human decision.', links: [], findings: 'Sample finding: define how half-cent amounts should round and add that case to the acceptance criteria. This is illustrative content, not a result of an executed review.', verdict: 'request_changes', failureReason: null, authorizedUsd: 0, usage: null, costStatus: 'unknown', keyAlias: null };
const details = Object.fromEntries(items.map(item => [item.id, { item, shifts: item.latestShift ? [item.latestShift] : [], runs: item.id === '101' ? [run] : item.id === '102' ? [{ ...run, id: '22', workItemId: item.id, shiftId: '12', role: 'implementer', writes: true, state: 'running', finishedAt: null, outcome: null, summary: '', stuckReason: '', findings: '', verdict: '' }] : [], checkpoints: item.id === '101' ? [{ id: '31', workItemId: item.id, phase: 'review', branch: shift.branch, prUrl: '', createdAt: at, nodeName: '', podUid: '' }] : [], events: [{ id: String(1000 + Number(item.id)), at, actor: 'demo-fixture', action: 'illustrative.snapshot', workItemId: item.id, team: item.team, detail: { reason: 'Illustrative operator data. No dispatch, model call or check was executed for this record.' } }], truncated: { shifts: false, runs: false, checkpoints: false, events: false } }])) as Record<string, PloegDetail>;

export const ploegDemo = { teams, items, details };
